# Configuration file that stores all hooks that pre-commit runs
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: no-commit-to-branch  # disallow commiting to master / main directly
        args: ['--branch', 'main', '--branch', 'master']
        stages: [commit]
      - id: check-yaml  # check yaml files for parsable syntax
        stages: [push]
      - id: check-toml  # checks toml files for parsable syntax
        stages: [push]
      - id: check-json  # checks json files for parsable syntax
        stages: [push]
      - id: check-added-large-files  # prevent large files from commit
        stages: [push]
      - id: check-merge-conflict  # checks for merge conflict strings
        stages: [push]
      - id: debug-statements  # checks for "breakpoint()" and debugger imports
        stages: [push]

  # Python hooks
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        stages: [push]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        stages: [push]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        stages: [push]
