name: ani-amber
channels:
  - nodefaults
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
dependencies:
  - python=3.8.1
  - pip

  # Required dependencies for torchani:
  - numpy>=1.24
  - pytorch=2.3
  - pytorch-cuda=11.8
  - typing_extensions>=4.0.0
  - h5py  # HDF5 backend for datasets
  - tqdm  # progress bar util

  # Needed for building cuaev / libtorch
  - nvidia::cuda-libraries-dev=11.8
  - nvidia::cuda-nvcc=11.8

  # pretty-printing
  - rich
