name: ani-amber
channels:
  - nodefaults
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/conda-forge
dependencies:
  ## Required dependencies of the TorchANI python package ##
  - python=3.10
  - pip>=24.0
  - typing_extensions>=4.0.0
  - numpy=1.26
  - pytorch::pytorch=2.3
  - pytorch::pytorch-cuda=11.8
  - h5py  # HDF5 backend for datasets
  - tqdm  # progress bar util
  - typer  # CLI support
  - rich  # CLI support

  # Extra dependencies needed to build compiled extensions, libcuaev and libtorchani
  - setuptools>=64
  - setuptools-scm>=8
  - gxx_linux-64=11.4
  - gcc_linux-64=11.4
  - nvidia::cuda-libraries-dev=11.8
  - nvidia::cuda-nvcc=11.8
  - nvidia::cuda-cccl=11.8
  - cmake>=3.24

  # Needed only to compile sander/pmememd serial and mpi
  - gfortran_linux-64=11.4
  - openmpi=4.1.5

  # Dev, not required
  - mypy
  - pre-commit  # runs pre commit/push hooks
  - black  # code formatter
  - flake8  # pep8 linter
  - autoflake  # remove unused imports / variables
