name: ani-amber
channels:
  - nodefaults
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/conda-forge
dependencies:
  ## Required dependencies to run TorchANI ##
  - python=3.10
  - pip>=24.0
  - numpy=1.26  # 1.26 required due to netCDF 4 for Amber
  - pytorch::pytorch=2.5  # Modify to 'pytorch::pytorch=2' if installing on macOS
  - typing_extensions>=4.0.0
  - h5py  # HDF5 backend for datasets
  - tqdm  # progress bar util
  - typer  # CLI support
  - rich  # CLI support

  # Optional dependencies follow:

  ## ASE interface ##
  # Used for molecular dynamics and for tests/tools/docs
  - ase

  ## NVIDIA CUDA GPU support ##
  - pytorch::pytorch-cuda=12.4  # Comment this line if installing on macOS, or to **disable** CUDA GPU support in any platform
  #- pytorch::cpuonly  # Uncomment this line to **disable** CUDA GPU support in Linux

  ## cuAEV and MNP ##
  # For more details consult the "developer notes" section in README.md
  # If installing on macOS, or if CUDA GPU support is **disabled**, comment all lines on this block
  - setuptools>=64
  - setuptools-scm>=8
  - gxx_linux-64=12.2
  - gcc_linux-64=12.2
  - gfortran_linux-64=12.2
  - nvidia::cuda-libraries-dev=12.4
  - nvidia::cuda-cccl=12.4
  - nvidia::cuda-nvcc=12.4
  - nvidia::cuda-cudart-static=12.4
  # Amber dependencies
  - conda-forge::fftw=3.3.10=mpi_openmpi_hdeb57f9_6  # For Sander / Pmemd
  - conda-forge::netcdf-fortran=4.6.1=mpi_openmpi_hc2a85ae_1  # For Sander / Pmemd
  - conda-forge::openmpi=4.1.6  # For MNP, Sander-MPI, and Pmemd-MPI
  - conda-forge::ucx  # For openmpi

  ## Running torchani-amber/tests ##
  - conda-forge::netcdf4
  ## Running torchani/tests ##
  - coverage  # code coverage
  - black  # formatter
  - flake8  # linter
  - mypy  # type checking
  - pytest  # tests runner
  - pre_commit  # run pre commit hooks
  - parameterized  # parametrize test classes
  - expecttest  # indirect dependency of torch.testing
  # Extra data backends for tests:
  - pandas  # Parquet backend
  - pyarrow  # Parquet backend
  - zarr  # Zarr backend

  ## Running scripts in torchani/tools ##
  - matplotlib
  - pynvml
  - jinja2  # Templating engine to build generated code and docs

  ## Building torchani/docs ##
  - sphinx
  - sphinx-design
  - sphinx-gallery
  - pydata-sphinx-theme
  - tensorboard

  # TorchANI-Amber specific
  - conda-forge::cmake=3.31.1

  # Extra
  - tinydb
  - pyyaml  # for mdrun
  - netCDF4
