name: ani-amber
channels:
  - nodefaults
dependencies:
  - python=3.8.1
  - pip
  - pytorch::pytorch=1.13.1=py3.8_cuda11.6_cudnn8.3.2_0
  - nvidia/label/cuda-11.6.1::cuda
  - conda-forge::numpy=1.20
  - conda-forge::cudnn=8.3.2
  - conda-forge::tqdm
