name: ani-amber
channels:
  - nodefaults
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/conda-forge
dependencies:
  ## Required dependencies to run TorchANI ##
  - python=3.11
  - conda-forge::pip>=24.0
  - conda-forge::numpy=1.26  # This is required by netcdf-fortran=4.6.1=mpi_openmpi_...
  - pytorch::pytorch=2.5  # Modify to 'pytorch::pytorch=2' if installing on macOS
  - conda-forge::typing_extensions>=4.0.0
  - conda-forge::h5py  # HDF5 backend for datasets
  - conda-forge::tqdm  # progress bar util
  - conda-forge::typer  # CLI support
  - conda-forge::rich  # CLI support
  - conda-forge::huggingface_hub  # Datasets

  # Optional dependencies follow:

  ## ASE interface ##
  # Used for molecular dynamics and for tests/tools/docs
  - conda-forge::ase

  ## NVIDIA CUDA GPU support ##
  - pytorch::pytorch-cuda=12.4  # Comment this line if installing on macOS, or to **disable** CUDA GPU support in any platform

  ## cuAEV and MNP ##
  # For more details consult the "developer notes" section in README.md
  # If installing on macOS, or if CUDA GPU support is **disabled**, comment all lines on this block
  - conda-forge::setuptools>=64
  - conda-forge::setuptools-scm>=8
  - conda-forge::gxx_linux-64=12.2
  - conda-forge::gcc_linux-64=12.2
  - conda-forge::gfortran_linux-64=12.2
  - nvidia::cuda-libraries-dev=12.4
  - nvidia::cuda-cccl=12.4
  - nvidia::cuda-nvcc=12.4
  - nvidia::cuda-cudart-static=12.4
  # Amber dependencies
  - conda-forge::fftw=3.3.10=mpi_openmpi_hdeb57f9_6  # For Sander / Pmemd
  # NetCDF-fortran *requires* numpy 1.26 (!) only if compiled with mpi_openmpi
  - conda-forge::netcdf-fortran=4.6.1=mpi_openmpi_hc2a85ae_1  # For Sander / Pmemd
  - conda-forge::openmpi=4.1.6  # For MNP, Sander-MPI, and Pmemd-MPI
  - conda-forge::ucx=1.18  # For openmpi

  ## Running torchani-amber/tests ##
  - conda-forge::netcdf4
  ## Running torchani/tests ##
  - black  # formatter
  - flake8  # linter
  - mypy  # type checking
  - pytest  # tests runner
  - pre_commit  # run pre commit hooks
  - parameterized  # parametrize test classes
  - expecttest  # indirect dependency of torch.testing
  # Extra data backends for tests:
  - pandas  # Parquet backend
  - pyarrow  # Parquet backend
  ## Running scripts in torchani/tools ##
  - jinja2  # Templating engine to build generated code and docs

  # TorchANI-Amber specific
  - conda-forge::cmake=3.31.1
  - conda-forge::tinydb
  - conda-forge::pyyaml
