name: ani-amber
channels:
  - nodefaults
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
dependencies:
  - python=3.10
  - pip

  # Required dependencies of the torchani python package:
  - numpy>=1.24
  - pytorch=2.3
  - pytorch-cuda=11.8
  - typing_extensions>=4.0.0
  - h5py  # HDF5 backend for datasets
  - tqdm  # progress bar util

  # Extra dependencies needed to build libcuaev and libtorchani
  - nvidia::cuda-libraries-dev=11.8
  - nvidia::cuda-nvcc=11.8
  - conda-forge::cudnn=8.9.7
  - cmake>=3.24
